# Generated by Django 4.2.7 on 2023-11-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_start", models.TimeField()),
                ("schedule_end", models.TimeField()),
                ("start_by_time", models.BooleanField()),
                ("is_open", models.BooleanField(default=False)),
            ],
        ),
    ]
