# Generated by Django 4.2.7 on 2023-11-23 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_client_user_ptr_delete_admin_delete_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_active",
            new_name="state",
        ),
        migrations.AlterField(
            model_name="mailcheck",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mail_check",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
