# Generated by Django 4.2.7 on 2023-11-19 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_admin_usercategory_userdetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetail",
            name="category",
        ),
        migrations.RemoveField(
            model_name="userdetail",
            name="content_type",
        ),
        migrations.DeleteModel(
            name="UserCategory",
        ),
        migrations.DeleteModel(
            name="UserDetail",
        ),
    ]
