# Generated by Django 4.2.7 on 2023-11-19 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_remove_userdetail_category_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Admin",
            new_name="User",
        ),
    ]
