# Generated by Django 4.2.7 on 2023-11-28 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_rename_is_active_user_state_alter_mailcheck_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
    ]
