# Generated by Django 4.2.7 on 2023-11-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_group_usergroup_delete_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.user",
                    ),
                ),
                ("phone_number", models.PositiveBigIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("user.user",),
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="group",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="user",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="UserGroup",
        ),
    ]
