# Generated by Django 4.2.7 on 2023-11-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_client_remove_usergroup_group_remove_usergroup_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mail",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
