# Generated by Django 4.2.7 on 2023-11-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_user_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.CharField(default="None", max_length=30),
        ),
    ]
