# Generated by Django 4.2.7 on 2023-11-19 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_user_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="group",
        ),
    ]
