# Generated by Django 4.2.7 on 2023-11-20 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_remove_user_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.user",
                    ),
                ),
                ("phone_number", models.PositiveBigIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("user.user",),
        ),
    ]
