# Generated by Django 4.2.7 on 2023-11-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprice",
            name="price",
            field=models.FloatField(),
        ),
    ]
