# Generated by Django 4.2.7 on 2023-11-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_rename_admin_user"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="orders",
                to="user.user",
            ),
        ),
    ]
