# Generated by Django 4.2.7 on 2023-11-29 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_discount_orderdiscount"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderdiscount",
            unique_together={("order", "discount")},
        ),
    ]
