# Generated by Django 4.2.7 on 2023-11-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_alter_orderdiscount_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCodePercentage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=15)),
                ("percentage", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
